Log:
  Level: info
  Formatter:
    Format: text

ExternalDomain: auth.localtest.me
ExternalPort: 80
ExternalSecure: false

TLS:
  Enabled: false

Database:
  Postgres:
    MaxOpenConns: 25
    MaxIdleConns: 10
    MaxConnLifetime: 1h
    MaxConnIdleTime: 5m

SystemDefaults:
  SecretGenerators:
    PasswordSaltCost: 14
    ClientSecretGenerator:
      Length: 64
      IncludeLowerLetters: true
      IncludeUpperLetters: true
      IncludeDigits: true
      IncludeSymbols: false
    InitializeUserCode:
      Length: 6
      Expiry: 72h
      IncludeLowerLetters: false
      IncludeUpperLetters: true
      IncludeDigits: true
      IncludeSymbols: false
    EmailVerificationCode:
      Length: 6
      Expiry: 1h
      IncludeLowerLetters: false
      IncludeUpperLetters: true
      IncludeDigits: true
      IncludeSymbols: false
    PhoneVerificationCode:
      Length: 6
      Expiry: 1h
      IncludeLowerLetters: false
      IncludeUpperLetters: false
      IncludeDigits: true
      IncludeSymbols: false
    DomainVerification:
      Length: 32
      IncludeLowerLetters: true
      IncludeUpperLetters: true
      IncludeDigits: true
      IncludeSymbols: false
    OTPSMS:
      Length: 8
      Expiry: 5m
      IncludeLowerLetters: false
      IncludeUpperLetters: false
      IncludeDigits: true
      IncludeSymbols: false
    OTPEmail:
      Length: 8
      Expiry: 5m
      IncludeLowerLetters: false
      IncludeUpperLetters: true
      IncludeDigits: true
      IncludeSymbols: false

DefaultInstance:
  OrgName: ShadowAPI
  DefaultLanguage: en


WebAuthN:
  ID: auth.localtest.me
  Origins:
    - http://auth.localtest.me

OIDC:
  DefaultAccessTokenLifetime: 12h
  DefaultIdTokenLifetime: 12h
  DefaultRefreshTokenIdleExpiration: 720h
  DefaultRefreshTokenExpiration: 720h

# Enable Management API
Management:
  Enabled: true

# API Configuration
API:
  GRPC:
    Port: 8080
  HTTP:
    Port: 8080