services:
  frontend:
    build:
      context: frontend
      dockerfile: ../devops/Dockerfile.frontend
    container_name: sa-frontend
    ports:
      - "5174:5174"
    networks:
      - shadowapi
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: ./frontend/package.json

  backend:
    build:
      context: .
      dockerfile: devops/Dockerfile.dev
    container_name: sa-backend
    working_dir: /app
    ports:
      - "8090:8090"
    depends_on:
      db:
        condition: service_healthy
      nats:
        condition: service_started
    environment:
      - SA_CONFIG_PATH=/app/config.yaml
    networks:
      - shadowapi
    volumes:
      - ./backend:/app/
      - ./db:/db/

  db:
    image: postgres:16-alpine
    container_name: sa-db
    restart: always
    networks:
      - shadowapi
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=shadowapi
      - POSTGRES_USER=shadowapi
      - POSTGRES_DB=shadowapi
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shadowapi"]
      interval: 5s
      timeout: 5s
      retries: 5

  nats:
    image: nats:2.11.1
    container_name: sa-nats
    command: ["-js", "--http_port=8222"]
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - shadowapi

volumes:
  postgres_data:

networks:
  shadowapi:
