include:
  - devops/compose/infra/compose.yaml
  - devops/compose/tools/compose.yaml

services:
  frontend:
    build:
      context: .
      dockerfile: devops/docker/frontend/dev.Dockerfile
    develop:
      watch:
        - action: sync
          path: ./front
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: ./front/package.json
    labels:
      - traefik.enable=true
      - traefik.http.routers.shadowapi-front.rule=Host(`${BE_DOMAIN}`)
      - traefik.http.routers.shadowapi-front.entrypoints=${BE_TRAEFIK_ENTRYPOINT}
      - traefik.http.routers.shadowapi-front.priority=1
      - traefik.http.services.shadowapi-front.loadbalancer.server.port=5173
    restart: always

  ssr:
    build:
      context: .
      dockerfile: devops/docker/ssr/dev.Dockerfile
    develop:
      watch:
        - action: sync
          path: ./front
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: ./front/package.json
    labels:
      - traefik.enable=true
      - traefik.http.routers.shadowapi-ssr.rule=Host(`${BE_DOMAIN}`) && PathPrefix(`/page`)
      - traefik.http.routers.shadowapi-ssr.entrypoints=${BE_TRAEFIK_ENTRYPOINT}
      - traefik.http.routers.shadowapi-ssr.priority=20
      - traefik.http.services.shadowapi-ssr.loadbalancer.server.port=3000
    restart: always

  backend:
    build:
      context: .
      dockerfile: devops/docker/backend/dev.Dockerfile
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
      traefik:
        condition: service_started
    environment:
      - BE_HOST=${BE_HOST}
      - BE_PORT=${BE_PORT}
      - BE_DB_URI=${BE_DB_URI}
      - BE_LOG_LEVEL=${BE_LOG_LEVEL}
      - BE_QUEUE_URL=${BE_QUEUE_URL}
      - BE_QUEUE_PREFIX=${BE_QUEUE_PREFIX}
    develop:
      watch:
        - action: rebuild
          path: ./backend
          ignore:
            - backend/tmp/
        - action: rebuild
          path: ./backend/go.mod
        - action: rebuild
          path: ./backend/go.sum
    labels:
      - traefik.enable=true
      - traefik.http.routers.shadowapi-api.rule=Host(`${BE_DOMAIN}`) && (PathPrefix(`/api/`) || PathPrefix(`/assets/`) || PathPrefix(`/auth/`))
      - traefik.http.routers.shadowapi-api.entrypoints=${BE_TRAEFIK_ENTRYPOINT}
      - traefik.http.routers.shadowapi-api.priority=30
      - traefik.http.services.shadowapi-api.loadbalancer.server.port=8080
    restart: always

  backend-loader:
    build:
      context: .
      dockerfile: devops/docker/loader/Dockerfile
    environment:
      - BE_HOST=${BE_HOST}
      - BE_DB_URI=${BE_DB_URI}
      - BE_LOG_LEVEL=${BE_LOG_LEVEL}
    depends_on:
      db:
        condition: service_healthy
    restart: always

