include:
  - devops/compose/infra/compose.yaml
  - devops/compose/zitadel/compose.yaml
  - devops/compose/tools/compose.yaml

services:
  frontend:
    build:
      context: .
      dockerfile: devops/docker/frontend/dev.Dockerfile
    volumes:
      - secrets:/secrets:ro
    develop:
      watch:
        - action: sync
          path: ./front
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: ./front/package.json
    labels:
      - traefik.enable=true
      - traefik.http.routers.shadowapi-front.rule=Host(`${BE_DOMAIN}`)
      - traefik.http.routers.shadowapi-front.entrypoints=${BE_TRAEFIK_ENTRYPOINT}
      - traefik.http.services.shadowapi-front.loadbalancer.server.port=5173
    restart: always

  backend:
    build:
      context: .
      dockerfile: devops/docker/backend/dev.Dockerfile
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
      zitadel:
        condition: service_started
      traefik:
        condition: service_started
    extra_hosts:
      - "auth.localtest.me:host-gateway"
    environment:
      - BE_HOST=${BE_HOST}
      - BE_PORT=${BE_PORT}
      - BE_DB_URI=${BE_DB_URI}
      - BE_LOG_LEVEL=${BE_LOG_LEVEL}
      - BE_QUEUE_URL=${BE_QUEUE_URL}
      - BE_QUEUE_PREFIX=${BE_QUEUE_PREFIX}
      - BE_AUTH_USER_MANAGER=${BE_AUTH_USER_MANAGER}
      - BE_ZITADEL_URL=${BE_ZITADEL_URL}
      - BE_ZITADEL_MANAGEMENT_URL=${BE_ZITADEL_MANAGEMENT_URL}
      - BE_ZITADEL_SERVICE_USER_KEY_PATH=${BE_ZITADEL_SERVICE_USER_KEY_PATH}
      - BE_ZITADEL_REDIRECT_URL=${BE_ZITADEL_REDIRECT_URL}
    volumes:
      - ./backend:/app/
      - ./spec:/spec/
      - secrets:/secrets:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.shadowapi-api.rule=Host(`${BE_DOMAIN}`) && (PathPrefix(`/api/`) || PathPrefix(`/assets/`) || PathPrefix(`/auth/`))
      - traefik.http.routers.shadowapi-api.entrypoints=${BE_TRAEFIK_ENTRYPOINT}
      - traefik.http.services.shadowapi-api.loadbalancer.server.port=8080
    restart: always

  backend-loader:
    build:
      context: .
      dockerfile: devops/docker/loader/Dockerfile
    environment:
      - BE_HOST=${BE_HOST}
      - BE_DB_URI=${BE_DB_URI}
      - BE_LOG_LEVEL=${BE_LOG_LEVEL}
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  secrets:
    driver: local
