version: "3"

tasks:
  init:
    desc: "Initialize development environment"
    cmds:
      - docker compose down -v
      - cp -f .env.example .env
      - docker compose run --rm db-migrate

  dev:
    desc: "Start development environment"
    cmds:
      - defer: docker compose down
      - docker compose up --watch 2>&1 | grep -vE '(db|traefik|zitadel)'

  db-shell:
    desc: "Open Postgres shell in the container"
    cmds:
      - docker compose exec db su - postgres -c "psql -U shadowapi shadowapi"

  api-gen:
    desc: "Generate API specs (backend & frontend)"
    deps:
      - go generate
      - npm run generate-api-client

  playwright-run:
    desc: "Run Playwright tests"
    dir: ./front
    cmds:
      - npx playwright test --headed
