frontend_assets_dir: "./dist"
log:
    level: ""
server:
    host: ""
    port: 0
db: {}
api:
    specs_dir: ""
jwt: {}
init_admin:
    email: ""
    password: ""
auth:
    ignore_https_error: false
    bearer_token: ""
    zitadel:
        instance_url: ""
        service_client_id: ""
        service_client_secret: ""
        api_key_file: ""
        audience: ""
        redirect_uri: ""
        intercepted_paths: []
worker:
    max_count: 0
queue:
    url: ""
    prefix: ""
