frontend_assets_dir: "./dist"
log:
    level: ""
server:
    host: ""
    port: 0
db:
    uri: "postgres://shadowapi:shadowapi@localhost:5432/shadowapi?sslmode=disable"
api:
    specs_dir: ""
jwt: {}
init_admin:
    email: ""
    password: ""
auth:
    ignore_https_error: false
    bearer_token: ""
    zitadel:
        instance_url: "https://example.zitadel.cloud"
        service_client_id: "client-id"
        service_client_secret: "client-secret"
        api_key_file: "./api-key.json"
        audience: "api-client-id"
        redirect_uri: "http://localtest.me/auth/callback"
        intercepted_paths:
            - "/.well-known/"
            - "/oauth/"
            - "/oidc/"
worker:
    max_count: 0
queue:
    url: "nats://localhost:4222"
    prefix: "shadowapi"
    username: ""
    password: ""
