// Code generated by ogen, DO NOT EDIT.
package api

type StoragePostgresTestInlineRes interface {
	storagePostgresTestInlineRes()
}

type StoragePostgresTestRes interface {
	storagePostgresTestRes()
}
