apiVersion: v1
kind: ConfigMap
metadata:
  name: shadowapi-config
data:
  SA_LOG_LEVEL: "DEBUG"
  SA_BASE_URL: "https://staging.shadowapi.devinlab.com"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shadowapi-ingress
spec:
  tls:
  - hosts:
    - staging.shadowapi.devinlab.com
    secretName: shadowapi-staging-tls
  rules:
  - host: staging.shadowapi.devinlab.com