services:
  db-migrate:
    image: arigaio/atlas:0.30.0
    command: >
      schema apply
      --url postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      --dev-url postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}_schema?sslmode=disable
      --to file://schema.sql
      --auto-approve
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../../../db/schema.sql:/schema.sql
    profiles:
      - tools
    restart: no

  sqlc:
    build:
      context: ../../..
      dockerfile: devops/docker/sqlc/Dockerfile
    image: sa-sqlc:1.28
    pull_policy: never
    profiles:
      - tools
    volumes:
      - ../../../db:/db
      - ../../../backend/pkg:/pkg
    working_dir: /db
