/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */
import type { DatasourceWhatsappSettings } from './datasourceWhatsappSettings';

/**
 * WhatsApp datasource object representation
 */
export interface DatasourceWhatsapp {
  readonly uuid?: string;
  readonly user_uuid: string;
  name: string;
  is_enabled?: boolean;
  provider: string;
  /** The phone number for the WhatsApp account */
  phone_number: string;
  /** Label for the WhatsApp device connection */
  device_name?: string;
  /** Additional WhatsApp bridging config from whatsapp.tpl.yaml 
(proxy, presence bridging, call notices, status broadcast, etc.)
 */
  settings?: DatasourceWhatsappSettings;
  readonly created_at?: string;
  readonly updated_at?: string;
}
