/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */
import type { DatasourceTelegramCreateDefaultErrorsItem } from './datasourceTelegramCreateDefaultErrorsItem';

export type DatasourceTelegramCreateDefault = {
  /** A human-readable explanation specific to this occurrence of the problem. */
  detail?: string;
  /** Optional list of individual error details */
  errors?: DatasourceTelegramCreateDefaultErrorsItem[];
  /** HTTP status code */
  status?: number;
};
