/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */

/**
 * Additional Telegram bridging config from telegram.tpl.yaml 
(proxy, concurrency, presence bridging, encryption, etc.)

 */
export type DatasourceTelegramList200ItemSettings = { [key: string]: unknown };
