/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */

export type DatasourceListParams = {
/**
 * The number of records to skip for pagination.
 */
offset?: number;
/**
 * The maximum number of records to return.
 */
limit?: number;
};
