/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */

/**
 * Arbitrary LinkedIn bridging config pulled from linkedin.tpl.yaml 
(presence bridging, encryption, etc.)

 */
export type DatasourceLinkedinSettings = { [key: string]: unknown };
