/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */
import type { DatasourceWhatsappUpdateDefaultErrorsItem } from './datasourceWhatsappUpdateDefaultErrorsItem';

export type DatasourceWhatsappUpdateDefault = {
  /** A human-readable explanation specific to this occurrence of the problem. */
  detail?: string;
  /** Optional list of individual error details */
  errors?: DatasourceWhatsappUpdateDefaultErrorsItem[];
  /** HTTP status code */
  status?: number;
};
