/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */
import type { GeneratePresignedUploadUrlBodyStorageType } from './generatePresignedUploadUrlBodyStorageType';

/**
 * Request to generate a pre-signed URL for upload.
 */
export type GeneratePresignedUploadUrlBody = {
  name?: string;
  mime_type?: string;
  /** The target storage backend. */
  storage_type?: GeneratePresignedUploadUrlBodyStorageType;
};
