/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */

/**
 * Response containing a signed download link.
 */
export type GenerateDownloadLink200 = {
  /** Signed URL for downloading the file. */
  url?: string;
};
