/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */

/**
 * Request to generate a download link.
 */
export interface GenerateDownloadLinkRequest {
  file_uuid?: string;
  /** Expiration time in seconds for the download link. */
  expiration?: number;
}
