/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */

/**
 * Platform or data source to query from.
 */
export type MessageQueryBodySource = typeof MessageQueryBodySource[keyof typeof MessageQueryBodySource];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageQueryBodySource = {
  email: 'email',
  whatsapp: 'whatsapp',
  telegram: 'telegram',
  linkedin: 'linkedin',
  custom: 'custom',
  unified: 'unified',
} as const;
