/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */

/**
 * Represents a stored file, independent of the storage backend.
 */
export type MessageQuery200MessagesItemAttachmentsItem = {
  /** Unique identifier for the file. */
  uuid?: string;
  /** Which storage backend is used, e.g. 's3', 'postgres', or 'hostfiles'. */
  storage_type: string;
  /** UUID referencing a 'storage' record (optional). */
  storage_uuid: string;
  /** Original filename. e.g. 'photo.jpg' or 'mail.raw'. */
  name: string;
  /** MIME type, e.g. 'application/pdf' or 'message/rfc822'. */
  mime_type?: string;
  /** Size in bytes. */
  size?: number;
  /** Optional. If storage_type='postgres', file content can be provided here (base64-encoded). */
  data?: Blob;
  /** Optional. If hostfiles or s3, the path or object key. e.g. 'my-bucket/xx/uuid.pdf'. */
  path?: string;
  /** Indicates if this file is the entire raw email. */
  is_raw?: boolean;
  /** Raw headers if needed (for emails or similar). */
  raw_headers?: string;
  /** Indicates whether the raw email is contained in this file. */
  has_raw_email?: boolean;
  /** Indicates if this is an inline/embedded file (e.g. images in HTML emails). */
  is_inline?: boolean;
  /** Timestamp when the file was created. */
  created_at?: string;
  /** Timestamp when the file was last modified. */
  updated_at?: string;
};
