/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */
import type { MessageWhatsappQuery200MessagesItemBodyParsedSubjectSlate } from './messageWhatsappQuery200MessagesItemBodyParsedSubjectSlate';
import type { MessageWhatsappQuery200MessagesItemBodyParsedBodySlate } from './messageWhatsappQuery200MessagesItemBodyParsedBodySlate';

export type MessageWhatsappQuery200MessagesItemBodyParsed = {
  /** Plain text representation of the subject. */
  subject_text?: string;
  /** Slate.js JSON representation of the subject. */
  subject_slate?: MessageWhatsappQuery200MessagesItemBodyParsedSubjectSlate;
  /** Plain text representation of the body. */
  body_text: string;
  /** Binary representation of the body (e.g., base64-encoded rich content). */
  body_byte?: string;
  /** Slate.js JSON representation of the message body. */
  body_slate?: MessageWhatsappQuery200MessagesItemBodyParsedBodySlate;
};
