/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */

/**
 * Additional context or metadata about the forwarded message.
 */
export type MessageEmailQuery200MessagesItemForwardMeta = { [key: string]: unknown };
