/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */

/**
 * Slate.js JSON representation of the message body.
 */
export type MessageWhatsappQuery200MessagesItemBodyParsedBodySlate = { [key: string]: unknown };
