/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */
import type { MessageTelegramQuery200MessagesItemBodyParsed } from './messageTelegramQuery200MessagesItemBodyParsed';
import type { MessageTelegramQuery200MessagesItemReactions } from './messageTelegramQuery200MessagesItemReactions';
import type { MessageTelegramQuery200MessagesItemAttachmentsItem } from './messageTelegramQuery200MessagesItemAttachmentsItem';
import type { MessageTelegramQuery200MessagesItemForwardMeta } from './messageTelegramQuery200MessagesItemForwardMeta';
import type { MessageTelegramQuery200MessagesItemMeta } from './messageTelegramQuery200MessagesItemMeta';

export type MessageTelegramQuery200MessagesItem = {
  /** Unique identifier for the message. */
  uuid?: string;
  /** Data source or platform the message originated from - email, whatsapp, telegram, linkedin, custom */
  type: string;
  /** Specifies the type or classification of the message - text, media, system, notification, attachment, invite, event, call */
  format: string;
  /** ID of the chat/conversation this message belongs to. */
  chat_uuid?: string;
  /** ID of a sub-thread if this message is part of a threaded conversation. */
  thread_uuid?: string;
  /** Original system's message ID (e.g., Gmail 'messageId'). */
  external_message_id?: string;
  /** Identifier of the user or account sending the message. */
  sender: string;
  /** List of users or accounts receiving the message (e.g., To, CC). */
  recipients: string[];
  /** Subject or title of the message (applicable to emails or similar). */
  subject?: string;
  /** Text content or body of the message. */
  body: string;
  body_parsed?: MessageTelegramQuery200MessagesItemBodyParsed;
  /** Collection of reactions (e.g., likes, emojis) applied to this message. */
  reactions?: MessageTelegramQuery200MessagesItemReactions;
  /** List of file attachments associated with this message. */
  attachments?: MessageTelegramQuery200MessagesItemAttachmentsItem[];
  /** ID or handle of the original sender if this message is forwarded. */
  forward_from?: string;
  /** ID of the message this one is directly replying to, if any. */
  reply_to_message_uuid?: string;
  /** ID of the original chat if this message is forwarded. */
  forward_from_chat_uuid?: string;
  /** ID of the original message if this is forwarded. */
  forward_from_message_uuid?: string;
  /** Additional context or metadata about the forwarded message. */
  forward_meta?: MessageTelegramQuery200MessagesItemForwardMeta;
  meta?: MessageTelegramQuery200MessagesItemMeta;
  /** The date and time when the object was created. */
  readonly created_at?: string;
  /** The date and time when the message was last updated. */
  updated_at?: string;
};
