/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */

/**
 * The state value (may include nonce, redirect_uri, etc.) used to prevent CSRF.
 */
export type Oauth2StateState = { [key: string]: unknown };
