/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */

export interface Oauth2Subject {
  /** Internal unique ID for the subject record. */
  uuid?: string;
  /** UUID of the user in the system. */
  user_uuid: string;
  /** UUID of the associated OAuth2 token record. */
  token_uuid: string;
  /** Timestamp when the subject record was created. */
  created_at?: string;
  /** Timestamp when the subject record was last updated. */
  updated_at?: string;
}
