/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */
import type { Oauth2ClientTokenListDefaultErrorsItem } from './oauth2ClientTokenListDefaultErrorsItem';

export type Oauth2ClientTokenListDefault = {
  /** A human-readable explanation specific to this occurrence of the problem. */
  detail?: string;
  /** Optional list of individual error details */
  errors?: Oauth2ClientTokenListDefaultErrorsItem[];
  /** HTTP status code */
  status?: number;
};
