/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */
import type { Oauth2ClientTokenList200ItemToken } from './oauth2ClientTokenList200ItemToken';

export type Oauth2ClientTokenList200Item = {
  /** Internal unique ID for the token record. */
  uuid?: string;
  /** UUID of the OAuth2 client that issued this token. */
  client_uuid: string;
  /** Optional. UUID of the user for whom the token was issued. */
  user_uuid?: string;
  token: Oauth2ClientTokenList200ItemToken;
  /** Timestamp when the token record was stored. */
  created_at?: string;
  /** Timestamp when the token record was last updated. */
  updated_at?: string;
};
