/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */
import type { Oauth2ClientDeleteDefaultErrorsItem } from './oauth2ClientDeleteDefaultErrorsItem';

export type Oauth2ClientDeleteDefault = {
  /** A human-readable explanation specific to this occurrence of the problem. */
  detail?: string;
  /** Optional list of individual error details */
  errors?: Oauth2ClientDeleteDefaultErrorsItem[];
  /** HTTP status code */
  status?: number;
};
