/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */
import type { PipelineFlowNodesItemPosition } from './pipelineFlowNodesItemPosition';
import type { PipelineFlowNodesItemData } from './pipelineFlowNodesItemData';

export type PipelineFlowNodesItem = {
  id: string;
  /** Required. Ex datasource, extractor, filter, storage */
  type: string;
  position: PipelineFlowNodesItemPosition;
  data: PipelineFlowNodesItemData;
};
