/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */
import type { PipelineUpdateBodyFlowNodesItemPosition } from './pipelineUpdateBodyFlowNodesItemPosition';
import type { PipelineUpdateBodyFlowNodesItemData } from './pipelineUpdateBodyFlowNodesItemData';

export type PipelineUpdateBodyFlowNodesItem = {
  id: string;
  /** Required. Ex datasource, extractor, filter, storage */
  type: string;
  position: PipelineUpdateBodyFlowNodesItemPosition;
  data: PipelineUpdateBodyFlowNodesItemData;
};
