/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */
import type { PipelineUpdate200FlowEdgesItemType } from './pipelineUpdate200FlowEdgesItemType';

export type PipelineUpdate200FlowEdgesItem = {
  id: string;
  source: string;
  target: string;
  type?: PipelineUpdate200FlowEdgesItemType;
};
