/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */

export type StorageListOrderDirection = typeof StorageListOrderDirection[keyof typeof StorageListOrderDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StorageListOrderDirection = {
  asc: 'asc',
  desc: 'desc',
} as const;
