/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */

/**
 * additional key-value settings for the sync policy.
 */
export type SyncpolicyGet200Settings = { [key: string]: unknown };
