/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */
import type { TelegramParticipantsItemMeta } from './telegramParticipantsItemMeta';

export type TelegramParticipantsItem = {
  /** Unique identifier of the participant (e.g. user ID) */
  participantId?: string;
  /** Arbitrary key-value metadata about the participant */
  meta?: TelegramParticipantsItemMeta;
};
