/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */
import type { TelegramParticipantsItem } from './telegramParticipantsItem';

/**
 * List of account participants
 */
export type TelegramParticipants = TelegramParticipantsItem[];
