/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShadowAPI
 * ShadowAPI server
 * OpenAPI spec version: 0.0.2
 */
import type { UploadFile200File } from './uploadFile200File';

/**
 * Response after uploading a file.
 */
export type UploadFile200 = {
  /** Represents a stored file, independent of the storage backend. */
  file?: UploadFile200File;
};
