apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "meshpump.fullname" . }}-migrate
  labels:
    {{- include "meshpump.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "meshpump.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: "{{ .Values.images.registry }}/shadowapi-migrate:{{ .Values.images.tag }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: DATABASE_URL
            - name: DEV_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.migrate.existingSecret }}
                  key: DEV_DATABASE_URL
