-- name: CreateContact :one
INSERT INTO contact (
    uuid,
    user_uuid,
    instance_uuid,
    status,
    names,
    names_search,
    last,
    first,
    middle,
    birthday,
    birthday_type,
    salary,
    salary_data,
    last_positions,
    last_position_id,
    last_position_company_id,
    last_position_company_name,
    last_position_title,
    last_position_start_date,
    last_position_end_date,
    last_position_end_now,
    last_position_description,
    note_search,
    note_kpi_id,
    phones,
    phone_search,
    phone1,
    phone1_type,
    phone1_country,
    phone2,
    phone2_type,
    phone2_country,
    phone3,
    phone3_type,
    phone3_country,
    phone4,
    phone4_type,
    phone4_country,
    phone5,
    phone5_type,
    phone5_country,
    emails,
    email_search,
    email1,
    email1_type,
    email2,
    email2_type,
    email3,
    email3_type,
    email4,
    email4_type,
    email5,
    email5_type,
    messengers,
    messengers_search,
    skype_uuid,
    skype,
    whatsapp_uuid,
    whatsapp,
    wechat_uuid,
    wechat,
    line_uuid,
    line,
    socials,
    socials_search,
    linkedin_uuid,
    linkedin_url,
    facebook_uuid,
    facebook_url,
    twitter_uuid,
    twitter_url,
    github_uuid,
    github_url,
    vk_uuid,
    vk_url,
    odno_uuid,
    odno_url,
    hhru_uuid,
    hhru_url,
    habr_uuid,
    habr_url,
    moikrug_uuid,
    moikrug_url,
    instagram_uuid,
    instagram_url,
    social1_uuid,
    social1_url,
    social1_type,
    social2_uuid,
    social2_url,
    social2_type,
    social3_uuid,
    social3_url,
    social3_type,
    social4_uuid,
    social4_url,
    social4_type,
    social5_uuid,
    social5_url,
    social5_type,
    social6_uuid,
    social6_url,
    social6_type,
    social7_uuid,
    social7_url,
    social7_type,
    social8_uuid,
    social8_url,
    social8_type,
    social9_uuid,
    social9_url,
    social9_type,
    tracking_source,
    tracking_slug,
    cached_img,
    cached_img_data,
    crawl,
    duplicate_user_id,
    duplicate_alternative_id,
    duplicate_report_date,
    entry_date,
    edit_date,
    last_kpi_entry_date
) VALUES (
             @uuid,
             @user_uuid,
             @instance_uuid,
             @status,
             @names,
             @names_search,
             @last,
             @first,
             @middle,
             @birthday,
             @birthday_type,
             @salary,
             @salary_data,
             @last_positions,
             @last_position_id,
             @last_position_company_id,
             @last_position_company_name,
             @last_position_title,
             @last_position_start_date,
             @last_position_end_date,
             @last_position_end_now,
             @last_position_description,
             @note_search,
             @note_kpi_id,
             @phones,
             @phone_search,
             @phone1,
             @phone1_type,
             @phone1_country,
             @phone2,
             @phone2_type,
             @phone2_country,
             @phone3,
             @phone3_type,
             @phone3_country,
             @phone4,
             @phone4_type,
             @phone4_country,
             @phone5,
             @phone5_type,
             @phone5_country,
             @emails,
             @email_search,
             @email1,
             @email1_type,
             @email2,
             @email2_type,
             @email3,
             @email3_type,
             @email4,
             @email4_type,
             @email5,
             @email5_type,
             @messengers,
             @messengers_search,
             @skype_uuid,
             @skype,
             @whatsapp_uuid,
             @whatsapp,
             @wechat_uuid,
             @wechat,
             @line_uuid,
             @line,
             @socials,
             @socials_search,
             @linkedin_uuid,
             @linkedin_url,
             @facebook_uuid,
             @facebook_url,
             @twitter_uuid,
             @twitter_url,
             @github_uuid,
             @github_url,
             @vk_uuid,
             @vk_url,
             @odno_uuid,
             @odno_url,
             @hhru_uuid,
             @hhru_url,
             @habr_uuid,
             @habr_url,
             @moikrug_uuid,
             @moikrug_url,
             @instagram_uuid,
             @instagram_url,
             @social1_uuid,
             @social1_url,
             @social1_type,
             @social2_uuid,
             @social2_url,
             @social2_type,
             @social3_uuid,
             @social3_url,
             @social3_type,
             @social4_uuid,
             @social4_url,
             @social4_type,
             @social5_uuid,
             @social5_url,
             @social5_type,
             @social6_uuid,
             @social6_url,
             @social6_type,
             @social7_uuid,
             @social7_url,
             @social7_type,
             @social8_uuid,
             @social8_url,
             @social8_type,
             @social9_uuid,
             @social9_url,
             @social9_type,
             @tracking_source,
             @tracking_slug,
             @cached_img,
             @cached_img_data,
             @crawl,
             @duplicate_user_id,
             @duplicate_alternative_id,
             @duplicate_report_date,
             @entry_date,
             @edit_date,
             @last_kpi_entry_date
         ) RETURNING *;

-- name: GetContact :one
SELECT
    *
FROM contact
WHERE
    uuid = @uuid
LIMIT 1;

-- name: ListContacts :many
SELECT
    *
FROM contact
ORDER BY entry_date DESC
LIMIT CASE WHEN @limit_records::int = 0 THEN NULL ELSE @limit_records::int END
    OFFSET @offset_records::int;

-- name: UpdateContact :exec
UPDATE contact
SET
    user_uuid                 = COALESCE(@user_uuid, user_uuid),
    instance_uuid             = COALESCE(@instance_uuid, instance_uuid),
    status                    = COALESCE(@status, status),
    names                     = COALESCE(@names, names),
    names_search              = COALESCE(@names_search, names_search),
    last                      = COALESCE(@last, last),
    first                     = COALESCE(@first, first),
    middle                    = COALESCE(@middle, middle),
    birthday                  = COALESCE(@birthday, birthday),
    birthday_type             = COALESCE(@birthday_type, birthday_type),
    salary                    = COALESCE(@salary, salary),
    salary_data               = COALESCE(@salary_data, salary_data),
    last_positions            = COALESCE(@last_positions, last_positions),
    last_position_id          = COALESCE(@last_position_id, last_position_id),
    last_position_company_id  = COALESCE(@last_position_company_id, last_position_company_id),
    last_position_company_name= COALESCE(@last_position_company_name, last_position_company_name),
    last_position_title       = COALESCE(@last_position_title, last_position_title),
    last_position_start_date  = COALESCE(@last_position_start_date, last_position_start_date),
    last_position_end_date    = COALESCE(@last_position_end_date, last_position_end_date),
    last_position_end_now     = COALESCE(@last_position_end_now, last_position_end_now),
    last_position_description = COALESCE(@last_position_description, last_position_description),
    note_search               = COALESCE(@note_search, note_search),
    note_kpi_id               = COALESCE(@note_kpi_id, note_kpi_id),
    phones                    = COALESCE(@phones, phones),
    phone_search              = COALESCE(@phone_search, phone_search),
    phone1                    = COALESCE(@phone1, phone1),
    phone1_type               = COALESCE(@phone1_type, phone1_type),
    phone1_country            = COALESCE(@phone1_country, phone1_country),
    phone2                    = COALESCE(@phone2, phone2),
    phone2_type               = COALESCE(@phone2_type, phone2_type),
    phone2_country            = COALESCE(@phone2_country, phone2_country),
    phone3                    = COALESCE(@phone3, phone3),
    phone3_type               = COALESCE(@phone3_type, phone3_type),
    phone3_country            = COALESCE(@phone3_country, phone3_country),
    phone4                    = COALESCE(@phone4, phone4),
    phone4_type               = COALESCE(@phone4_type, phone4_type),
    phone4_country            = COALESCE(@phone4_country, phone4_country),
    phone5                    = COALESCE(@phone5, phone5),
    phone5_type               = COALESCE(@phone5_type, phone5_type),
    phone5_country            = COALESCE(@phone5_country, phone5_country),
    emails                    = COALESCE(@emails, emails),
    email_search              = COALESCE(@email_search, email_search),
    email1                    = COALESCE(@email1, email1),
    email1_type               = COALESCE(@email1_type, email1_type),
    email2                    = COALESCE(@email2, email2),
    email2_type               = COALESCE(@email2_type, email2_type),
    email3                    = COALESCE(@email3, email3),
    email3_type               = COALESCE(@email3_type, email3_type),
    email4                    = COALESCE(@email4, email4),
    email4_type               = COALESCE(@email4_type, email4_type),
    email5                    = COALESCE(@email5, email5),
    email5_type               = COALESCE(@email5_type, email5_type),
    messengers                = COALESCE(@messengers, messengers),
    messengers_search         = COALESCE(@messengers_search, messengers_search),
    skype_uuid                = COALESCE(@skype_uuid, skype_uuid),
    skype                     = COALESCE(@skype, skype),
    whatsapp_uuid             = COALESCE(@whatsapp_uuid, whatsapp_uuid),
    whatsapp                  = COALESCE(@whatsapp, whatsapp),
    wechat_uuid               = COALESCE(@wechat_uuid, wechat_uuid),
    wechat                    = COALESCE(@wechat, wechat),
    line_uuid                 = COALESCE(@line_uuid, line_uuid),
    line                      = COALESCE(@line, line),
    socials                   = COALESCE(@socials, socials),
    socials_search            = COALESCE(@socials_search, socials_search),
    linkedin_uuid             = COALESCE(@linkedin_uuid, linkedin_uuid),
    linkedin_url              = COALESCE(@linkedin_url, linkedin_url),
    facebook_uuid             = COALESCE(@facebook_uuid, facebook_uuid),
    facebook_url              = COALESCE(@facebook_url, facebook_url),
    twitter_uuid              = COALESCE(@twitter_uuid, twitter_uuid),
    twitter_url               = COALESCE(@twitter_url, twitter_url),
    github_uuid               = COALESCE(@github_uuid, github_uuid),
    github_url                = COALESCE(@github_url, github_url),
    vk_uuid                   = COALESCE(@vk_uuid, vk_uuid),
    vk_url                    = COALESCE(@vk_url, vk_url),
    odno_uuid                 = COALESCE(@odno_uuid, odno_uuid),
    odno_url                  = COALESCE(@odno_url, odno_url),
    hhru_uuid                 = COALESCE(@hhru_uuid, hhru_uuid),
    hhru_url                  = COALESCE(@hhru_url, hhru_url),
    habr_uuid                 = COALESCE(@habr_uuid, habr_uuid),
    habr_url                  = COALESCE(@habr_url, habr_url),
    moikrug_uuid              = COALESCE(@moikrug_uuid, moikrug_uuid),
    moikrug_url               = COALESCE(@moikrug_url, moikrug_url),
    instagram_uuid            = COALESCE(@instagram_uuid, instagram_uuid),
    instagram_url             = COALESCE(@instagram_url, instagram_url),
    social1_uuid              = COALESCE(@social1_uuid, social1_uuid),
    social1_url               = COALESCE(@social1_url, social1_url),
    social1_type              = COALESCE(@social1_type, social1_type),
    social2_uuid              = COALESCE(@social2_uuid, social2_uuid),
    social2_url               = COALESCE(@social2_url, social2_url),
    social2_type              = COALESCE(@social2_type, social2_type),
    social3_uuid              = COALESCE(@social3_uuid, social3_uuid),
    social3_url               = COALESCE(@social3_url, social3_url),
    social3_type              = COALESCE(@social3_type, social3_type),
    social4_uuid              = COALESCE(@social4_uuid, social4_uuid),
    social4_url               = COALESCE(@social4_url, social4_url),
    social4_type              = COALESCE(@social4_type, social4_type),
    social5_uuid              = COALESCE(@social5_uuid, social5_uuid),
    social5_url               = COALESCE(@social5_url, social5_url),
    social5_type              = COALESCE(@social5_type, social5_type),
    social6_uuid              = COALESCE(@social6_uuid, social6_uuid),
    social6_url               = COALESCE(@social6_url, social6_url),
    social6_type              = COALESCE(@social6_type, social6_type),
    social7_uuid              = COALESCE(@social7_uuid, social7_uuid),
    social7_url               = COALESCE(@social7_url, social7_url),
    social7_type              = COALESCE(@social7_type, social7_type),
    social8_uuid              = COALESCE(@social8_uuid, social8_uuid),
    social8_url               = COALESCE(@social8_url, social8_url),
    social8_type              = COALESCE(@social8_type, social8_type),
    social9_uuid              = COALESCE(@social9_uuid, social9_uuid),
    social9_url               = COALESCE(@social9_url, social9_url),
    social9_type              = COALESCE(@social9_type, social9_type),
    tracking_source           = COALESCE(@tracking_source, tracking_source),
    tracking_slug             = COALESCE(@tracking_slug, tracking_slug),
    cached_img                = COALESCE(@cached_img, cached_img),
    cached_img_data           = COALESCE(@cached_img_data, cached_img_data),
    crawl                     = COALESCE(@crawl, crawl),
    duplicate_user_id         = COALESCE(@duplicate_user_id, duplicate_user_id),
    duplicate_alternative_id  = COALESCE(@duplicate_alternative_id, duplicate_alternative_id),
    duplicate_report_date     = COALESCE(@duplicate_report_date, duplicate_report_date),
    entry_date                = COALESCE(@entry_date, entry_date),
    edit_date                 = COALESCE(@edit_date, edit_date),
    last_kpi_entry_date       = COALESCE(@last_kpi_entry_date, last_kpi_entry_date)
WHERE uuid = @uuid;

-- name: DeleteContact :exec
DELETE FROM contact
WHERE uuid = @uuid;