type: object
additionalProperties: false
properties:
  uuid:
    type: string
    description: Unique identifier
  datasource_uuid:
    type: string
  storage_uuid:
    type: string
  type:
    type: string
    description: Pipeline type (email, telegram, whatsapp, linkedin) pulled from datasource_uuid
  name:
    type: string
    description: Pipeline name
  is_enabled:
    type: boolean
    description: Whether this pipeline is currently active
  flow:
    type: object
    description: JSON representation of the flow (compatible with @xyflow/react)
    properties:
      nodes:
        type: array
        items:
          $ref: "../openapi.yaml#/components/schemas/PipelineNode"
      edges:
        type: array
        items:
          $ref: "../openapi.yaml#/components/schemas/PipelineEdge"
  created_at:
    type: string
    format: date-time
    description: "Timestamp when the policy was created."
  updated_at:
    type: string
    format: date-time
    description: "Timestamp when the policy was last updated."
required:
  - datasource_uuid
  - storage_uuid
  - name