type: object
additionalProperties: false
properties:
  uuid:
    type: string
  user_uuid:
    type: string
    description: The user (or account) that owns this pipeline.
    readOnly: true
  name:
    type: string
  flow:
    type: object
    additionalProperties: true
  created_at:
    format: date-time
    type: string
  updated_at:
    format: date-time
    type: string
required:
  - uuid
  - name
  - flow
