type: object
additionalProperties: false
properties:
  uuid:
    type: string
  name:
    type: string
  flow:
    type: object
    additionalProperties: true
  created_at:
    format: date-time
    type: string
  updated_at:
    format: date-time
    type: string
required:
  - uuid
  - datasource_uuid
  - name
  - flow
