// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package query

import (
	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Datasource struct {
	UUID          uuid.UUID          `json:"uuid"`
	WorkspaceUUID *uuid.UUID         `json:"workspace_uuid"`
	UserUUID      *uuid.UUID         `json:"user_uuid"`
	Name          string             `json:"name"`
	Type          string             `json:"type"`
	IsEnabled     bool               `json:"is_enabled"`
	Provider      string             `json:"provider"`
	Settings      []byte             `json:"settings"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type LadonPolicy struct {
	ID          string             `json:"id"`
	Description pgtype.Text        `json:"description"`
	Effect      string             `json:"effect"`
	Conditions  []byte             `json:"conditions"`
	Meta        []byte             `json:"meta"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type LadonPolicyAction struct {
	ID       int32  `json:"id"`
	PolicyID string `json:"policy_id"`
	Action   string `json:"action"`
}

type LadonPolicyResource struct {
	ID       int32  `json:"id"`
	PolicyID string `json:"policy_id"`
	Resource string `json:"resource"`
}

type LadonPolicySubject struct {
	ID       int32  `json:"id"`
	PolicyID string `json:"policy_id"`
	Subject  string `json:"subject"`
}

type Oauth2Client struct {
	UUID          uuid.UUID          `json:"uuid"`
	WorkspaceUUID *uuid.UUID         `json:"workspace_uuid"`
	Name          string             `json:"name"`
	Provider      string             `json:"provider"`
	ClientID      string             `json:"client_id"`
	Secret        string             `json:"secret"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Oauth2State struct {
	UUID       uuid.UUID          `json:"uuid"`
	ClientUuid *uuid.UUID         `json:"client_uuid"`
	State      []byte             `json:"state"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ExpiredAt  pgtype.Timestamptz `json:"expired_at"`
}

type Oauth2Subject struct {
	UUID      uuid.UUID          `json:"uuid"`
	UserUUID  *uuid.UUID         `json:"user_uuid"`
	TokenUuid *uuid.UUID         `json:"token_uuid"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Oauth2Token struct {
	UUID       uuid.UUID          `json:"uuid"`
	ClientUuid *uuid.UUID         `json:"client_uuid"`
	UserUUID   *uuid.UUID         `json:"user_uuid"`
	Token      []byte             `json:"token"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Name       pgtype.Text        `json:"name"`
}

type PasswordReset struct {
	UUID      uuid.UUID          `json:"uuid"`
	UserUUID  *uuid.UUID         `json:"user_uuid"`
	Email     string             `json:"email"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Permission struct {
	UUID        uuid.UUID          `json:"uuid"`
	Name        string             `json:"name"`
	DisplayName string             `json:"display_name"`
	Description pgtype.Text        `json:"description"`
	Resource    string             `json:"resource"`
	Action      string             `json:"action"`
	Scope       string             `json:"scope"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Pipeline struct {
	UUID           uuid.UUID          `json:"uuid"`
	WorkspaceUUID  *uuid.UUID         `json:"workspace_uuid"`
	DatasourceUUID *uuid.UUID         `json:"datasource_uuid"`
	StorageUuid    *uuid.UUID         `json:"storage_uuid"`
	WorkerUUID     *uuid.UUID         `json:"worker_uuid"`
	Name           string             `json:"name"`
	Type           string             `json:"type"`
	IsEnabled      bool               `json:"is_enabled"`
	Flow           []byte             `json:"flow"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PolicySet struct {
	UUID        uuid.UUID          `json:"uuid"`
	Name        string             `json:"name"`
	DisplayName string             `json:"display_name"`
	Description pgtype.Text        `json:"description"`
	Scope       string             `json:"scope"`
	IsSystem    bool               `json:"is_system"`
	Permissions []byte             `json:"permissions"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RegisteredWorker struct {
	UUID            uuid.UUID          `json:"uuid"`
	Name            string             `json:"name"`
	SecretHash      string             `json:"secret_hash"`
	Status          string             `json:"status"`
	IsGlobal        bool               `json:"is_global"`
	Version         pgtype.Text        `json:"version"`
	Labels          []byte             `json:"labels"`
	LastHeartbeat   pgtype.Timestamptz `json:"last_heartbeat"`
	LastConnectedAt pgtype.Timestamptz `json:"last_connected_at"`
	ConnectedFrom   pgtype.Text        `json:"connected_from"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Scheduler struct {
	UUID                uuid.UUID          `json:"uuid"`
	PipelineUuid        *uuid.UUID         `json:"pipeline_uuid"`
	ScheduleType        string             `json:"schedule_type"`
	CronExpression      pgtype.Text        `json:"cron_expression"`
	RunAt               pgtype.Timestamptz `json:"run_at"`
	Timezone            string             `json:"timezone"`
	NextRun             pgtype.Timestamptz `json:"next_run"`
	LastRun             pgtype.Timestamptz `json:"last_run"`
	LastUid             int64              `json:"last_uid"`
	IsEnabled           bool               `json:"is_enabled"`
	IsPaused            bool               `json:"is_paused"`
	BatchSize           int32              `json:"batch_size"`
	SyncState           pgtype.Text        `json:"sync_state"`
	LastSyncTimestamp   pgtype.Timestamptz `json:"last_sync_timestamp"`
	OldestSyncTimestamp pgtype.Timestamptz `json:"oldest_sync_timestamp"`
	CutoffDate          pgtype.Timestamptz `json:"cutoff_date"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Storage struct {
	UUID          uuid.UUID          `json:"uuid"`
	WorkspaceUUID *uuid.UUID         `json:"workspace_uuid"`
	Name          string             `json:"name"`
	Type          string             `json:"type"`
	IsEnabled     bool               `json:"is_enabled"`
	Settings      []byte             `json:"settings"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type SyncPolicy struct {
	UUID         uuid.UUID          `json:"uuid"`
	PipelineUuid *uuid.UUID         `json:"pipeline_uuid"`
	Name         string             `json:"name"`
	Type         string             `json:"type"`
	Blocklist    []string           `json:"blocklist"`
	ExcludeList  []string           `json:"exclude_list"`
	SyncAll      bool               `json:"sync_all"`
	IsEnabled    bool               `json:"is_enabled"`
	Settings     []byte             `json:"settings"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type TgAccount struct {
	ID       int64       `json:"id"`
	Username pgtype.Text `json:"username"`
}

type TgCachedChannel struct {
	ID          int64       `json:"id"`
	Title       pgtype.Text `json:"title"`
	Username    pgtype.Text `json:"username"`
	Broadcast   pgtype.Bool `json:"broadcast"`
	Forum       pgtype.Bool `json:"forum"`
	Megagroup   pgtype.Bool `json:"megagroup"`
	Raw         []byte      `json:"raw"`
	RawFull     []byte      `json:"raw_full"`
	FkSessionID int64       `json:"fk_session_id"`
}

type TgCachedChat struct {
	ID          int64       `json:"id"`
	Title       pgtype.Text `json:"title"`
	Raw         []byte      `json:"raw"`
	RawFull     []byte      `json:"raw_full"`
	FkSessionID int64       `json:"fk_session_id"`
}

type TgCachedUser struct {
	ID          int64       `json:"id"`
	FirstName   pgtype.Text `json:"first_name"`
	LastName    pgtype.Text `json:"last_name"`
	Username    pgtype.Text `json:"username"`
	Phone       pgtype.Text `json:"phone"`
	Raw         []byte      `json:"raw"`
	RawFull     []byte      `json:"raw_full"`
	FkSessionID int64       `json:"fk_session_id"`
}

type TgPeer struct {
	ID          int64       `json:"id"`
	FkSessionID int64       `json:"fk_session_id"`
	PeerType    string      `json:"peer_type"`
	AccessHash  pgtype.Int8 `json:"access_hash"`
}

type TgPeersChannel struct {
	ID          int64 `json:"id"`
	FkSessionID int64 `json:"fk_session_id"`
	Pts         int64 `json:"pts"`
}

type TgPeersUser struct {
	ID          int64       `json:"id"`
	FkSessionID int64       `json:"fk_session_id"`
	Phone       pgtype.Text `json:"phone"`
}

type TgSession struct {
	ID           int64              `json:"id"`
	Phone        string             `json:"phone"`
	AccountID    int64              `json:"account_id"`
	Session      []byte             `json:"session"`
	ContactsHash pgtype.Int8        `json:"contacts_hash"`
	Description  pgtype.Text        `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type TgSessionsState struct {
	ID   int64 `json:"id"`
	Pts  int64 `json:"pts"`
	Qts  int64 `json:"qts"`
	Date int64 `json:"date"`
	Seq  int64 `json:"seq"`
}

type UsageLimit struct {
	UUID          uuid.UUID          `json:"uuid"`
	PolicySetName string             `json:"policy_set_name"`
	LimitType     string             `json:"limit_type"`
	LimitValue    pgtype.Int8        `json:"limit_value"`
	ResetPeriod   string             `json:"reset_period"`
	IsEnabled     bool               `json:"is_enabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	UUID      uuid.UUID          `json:"uuid"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	IsEnabled bool               `json:"is_enabled"`
	Meta      []byte             `json:"meta"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserInvite struct {
	UUID              uuid.UUID          `json:"uuid"`
	WorkspaceUUID     *uuid.UUID         `json:"workspace_uuid"`
	Email             string             `json:"email"`
	PolicySetName     string             `json:"policy_set_name"`
	TokenHash         string             `json:"token_hash"`
	InvitedByUserUuid *uuid.UUID         `json:"invited_by_user_uuid"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt        pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type UserPolicySet struct {
	UUID          uuid.UUID          `json:"uuid"`
	UserUUID      *uuid.UUID         `json:"user_uuid"`
	PolicySetName string             `json:"policy_set_name"`
	WorkspaceSlug pgtype.Text        `json:"workspace_slug"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type UserUsageLimitOverride struct {
	UUID          uuid.UUID          `json:"uuid"`
	UserUUID      *uuid.UUID         `json:"user_uuid"`
	WorkspaceSlug string             `json:"workspace_slug"`
	LimitType     string             `json:"limit_type"`
	LimitValue    pgtype.Int8        `json:"limit_value"`
	ResetPeriod   pgtype.Text        `json:"reset_period"`
	IsEnabled     bool               `json:"is_enabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type UserUsageTracking struct {
	UUID          uuid.UUID          `json:"uuid"`
	UserUUID      *uuid.UUID         `json:"user_uuid"`
	WorkspaceSlug string             `json:"workspace_slug"`
	LimitType     string             `json:"limit_type"`
	PeriodStart   pgtype.Timestamptz `json:"period_start"`
	PeriodEnd     pgtype.Timestamptz `json:"period_end"`
	CurrentUsage  int64              `json:"current_usage"`
	LastUpdated   pgtype.Timestamptz `json:"last_updated"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type WorkerEnrollmentToken struct {
	UUID              uuid.UUID          `json:"uuid"`
	TokenHash         string             `json:"token_hash"`
	Name              string             `json:"name"`
	IsGlobal          bool               `json:"is_global"`
	WorkspaceUuids    []pgtype.UUID      `json:"workspace_uuids"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	UsedAt            pgtype.Timestamptz `json:"used_at"`
	UsedByWorkerUuid  *uuid.UUID         `json:"used_by_worker_uuid"`
	CreatedByUserUuid *uuid.UUID         `json:"created_by_user_uuid"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type WorkerJob struct {
	UUID          uuid.UUID          `json:"uuid"`
	SchedulerUuid *uuid.UUID         `json:"scheduler_uuid"`
	JobUuid       *uuid.UUID         `json:"job_uuid"`
	Subject       string             `json:"subject"`
	Status        string             `json:"status"`
	Data          []byte             `json:"data"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
}

type WorkerUsageLimit struct {
	UUID          uuid.UUID          `json:"uuid"`
	WorkerUUID    *uuid.UUID         `json:"worker_uuid"`
	WorkspaceSlug string             `json:"workspace_slug"`
	LimitType     string             `json:"limit_type"`
	LimitValue    pgtype.Int8        `json:"limit_value"`
	ResetPeriod   string             `json:"reset_period"`
	IsEnabled     bool               `json:"is_enabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type WorkerUsageTracking struct {
	UUID          uuid.UUID          `json:"uuid"`
	WorkerUUID    *uuid.UUID         `json:"worker_uuid"`
	WorkspaceSlug string             `json:"workspace_slug"`
	LimitType     string             `json:"limit_type"`
	PeriodStart   pgtype.Timestamptz `json:"period_start"`
	PeriodEnd     pgtype.Timestamptz `json:"period_end"`
	CurrentUsage  int64              `json:"current_usage"`
	LastUpdated   pgtype.Timestamptz `json:"last_updated"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type WorkerWorkspace struct {
	UUID          uuid.UUID          `json:"uuid"`
	WorkerUUID    *uuid.UUID         `json:"worker_uuid"`
	WorkspaceUUID *uuid.UUID         `json:"workspace_uuid"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Workspace struct {
	UUID        uuid.UUID          `json:"uuid"`
	Slug        string             `json:"slug"`
	DisplayName string             `json:"display_name"`
	IsEnabled   bool               `json:"is_enabled"`
	Settings    []byte             `json:"settings"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceMember struct {
	UUID          uuid.UUID          `json:"uuid"`
	WorkspaceUUID *uuid.UUID         `json:"workspace_uuid"`
	UserUUID      *uuid.UUID         `json:"user_uuid"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
