// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tenant.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenant (
    uuid,
    name,
    display_name,
    is_enabled,
    settings,
    created_at
) VALUES (
    $1::uuid,
    $2,
    $3,
    $4::boolean,
    $5,
    NOW()
) RETURNING uuid, name, display_name, is_enabled, settings, created_at, updated_at
`

type CreateTenantParams struct {
	UUID        pgtype.UUID `json:"uuid"`
	Name        string      `json:"name"`
	DisplayName string      `json:"display_name"`
	IsEnabled   bool        `json:"is_enabled"`
	Settings    []byte      `json:"settings"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.UUID,
		arg.Name,
		arg.DisplayName,
		arg.IsEnabled,
		arg.Settings,
	)
	var i Tenant
	err := row.Scan(
		&i.UUID,
		&i.Name,
		&i.DisplayName,
		&i.IsEnabled,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenant WHERE uuid = $1::uuid
`

func (q *Queries) DeleteTenant(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenant, uuid)
	return err
}

const getTenant = `-- name: GetTenant :one
SELECT uuid, name, display_name, is_enabled, settings, created_at, updated_at FROM tenant WHERE uuid = $1::uuid
`

func (q *Queries) GetTenant(ctx context.Context, uuid pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, uuid)
	var i Tenant
	err := row.Scan(
		&i.UUID,
		&i.Name,
		&i.DisplayName,
		&i.IsEnabled,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByName = `-- name: GetTenantByName :one
SELECT uuid, name, display_name, is_enabled, settings, created_at, updated_at FROM tenant WHERE name = $1
`

func (q *Queries) GetTenantByName(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByName, name)
	var i Tenant
	err := row.Scan(
		&i.UUID,
		&i.Name,
		&i.DisplayName,
		&i.IsEnabled,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledTenants = `-- name: ListEnabledTenants :many
SELECT uuid, name, display_name, is_enabled, settings, created_at, updated_at FROM tenant
WHERE is_enabled = true
ORDER BY display_name ASC
LIMIT NULLIF($2::int, 0)
OFFSET $1
`

type ListEnabledTenantsParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListEnabledTenants(ctx context.Context, arg ListEnabledTenantsParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listEnabledTenants, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.UUID,
			&i.Name,
			&i.DisplayName,
			&i.IsEnabled,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT uuid, name, display_name, is_enabled, settings, created_at, updated_at FROM tenant
ORDER BY display_name ASC
LIMIT NULLIF($2::int, 0)
OFFSET $1
`

type ListTenantsParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.UUID,
			&i.Name,
			&i.DisplayName,
			&i.IsEnabled,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenant = `-- name: UpdateTenant :exec
UPDATE tenant SET
    display_name = $1,
    is_enabled = $2::boolean,
    settings = $3,
    updated_at = NOW()
WHERE uuid = $4::uuid
`

type UpdateTenantParams struct {
	DisplayName string      `json:"display_name"`
	IsEnabled   bool        `json:"is_enabled"`
	Settings    []byte      `json:"settings"`
	UUID        pgtype.UUID `json:"uuid"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) error {
	_, err := q.db.Exec(ctx, updateTenant,
		arg.DisplayName,
		arg.IsEnabled,
		arg.Settings,
		arg.UUID,
	)
	return err
}
