// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: worker_workspace.sql

package query

import (
	"context"

	"github.com/gofrs/uuid"
)

const addWorkerWorkspace = `-- name: AddWorkerWorkspace :exec
INSERT INTO worker_workspace (uuid, worker_uuid, workspace_uuid, created_at)
VALUES ($1, $2, $3, NOW())
`

type AddWorkerWorkspaceParams struct {
	UUID          uuid.UUID  `json:"uuid"`
	WorkerUUID    *uuid.UUID `json:"worker_uuid"`
	WorkspaceUUID *uuid.UUID `json:"workspace_uuid"`
}

func (q *Queries) AddWorkerWorkspace(ctx context.Context, arg AddWorkerWorkspaceParams) error {
	_, err := q.db.Exec(ctx, addWorkerWorkspace, arg.UUID, arg.WorkerUUID, arg.WorkspaceUUID)
	return err
}

const getWorkerWorkspaces = `-- name: GetWorkerWorkspaces :many
SELECT w.uuid, w.slug, w.display_name, w.is_enabled, w.settings, w.created_at, w.updated_at FROM workspace w
JOIN worker_workspace ww ON w.uuid = ww.workspace_uuid
WHERE ww.worker_uuid = $1
`

func (q *Queries) GetWorkerWorkspaces(ctx context.Context, workerUuid *uuid.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, getWorkerWorkspaces, workerUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.UUID,
			&i.Slug,
			&i.DisplayName,
			&i.IsEnabled,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceWorkers = `-- name: GetWorkspaceWorkers :many
SELECT rw.uuid, rw.name, rw.secret_hash, rw.status, rw.is_global, rw.version, rw.labels, rw.last_heartbeat, rw.last_connected_at, rw.connected_from, rw.created_at, rw.updated_at FROM registered_worker rw
JOIN worker_workspace ww ON rw.uuid = ww.worker_uuid
WHERE ww.workspace_uuid = $1
`

func (q *Queries) GetWorkspaceWorkers(ctx context.Context, workspaceUuid *uuid.UUID) ([]RegisteredWorker, error) {
	rows, err := q.db.Query(ctx, getWorkspaceWorkers, workspaceUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegisteredWorker
	for rows.Next() {
		var i RegisteredWorker
		if err := rows.Scan(
			&i.UUID,
			&i.Name,
			&i.SecretHash,
			&i.Status,
			&i.IsGlobal,
			&i.Version,
			&i.Labels,
			&i.LastHeartbeat,
			&i.LastConnectedAt,
			&i.ConnectedFrom,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkerWorkspaceLinks = `-- name: ListWorkerWorkspaceLinks :many
SELECT uuid, worker_uuid, workspace_uuid, created_at FROM worker_workspace
WHERE worker_uuid = $1
`

func (q *Queries) ListWorkerWorkspaceLinks(ctx context.Context, workerUuid *uuid.UUID) ([]WorkerWorkspace, error) {
	rows, err := q.db.Query(ctx, listWorkerWorkspaceLinks, workerUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkerWorkspace
	for rows.Next() {
		var i WorkerWorkspace
		if err := rows.Scan(
			&i.UUID,
			&i.WorkerUUID,
			&i.WorkspaceUUID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWorkerWorkspace = `-- name: RemoveWorkerWorkspace :exec
DELETE FROM worker_workspace
WHERE worker_uuid = $1 AND workspace_uuid = $2
`

type RemoveWorkerWorkspaceParams struct {
	WorkerUUID    *uuid.UUID `json:"worker_uuid"`
	WorkspaceUUID *uuid.UUID `json:"workspace_uuid"`
}

func (q *Queries) RemoveWorkerWorkspace(ctx context.Context, arg RemoveWorkerWorkspaceParams) error {
	_, err := q.db.Exec(ctx, removeWorkerWorkspace, arg.WorkerUUID, arg.WorkspaceUUID)
	return err
}
