apiVersion: v1
kind: ConfigMap
metadata:
  name: shadowapi-config
  namespace: shadowapi
data:
  SA_HOST: "0.0.0.0"
  SA_PORT: "8080"
  SA_LOG_LEVEL: "INFO"
  SA_ENV: "production"
  SA_QUEUE_URL: "nats://nats:4222"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kratos-config
  namespace: shadowapi
data:
  kratos.yaml: |
    version: v1.3.1
    
    dsn: postgres://user:password@host:port/database
    
    serve:
      public:
        base_url: https://shadowapi.devinlab.com/auth/user
        cors:
          enabled: true
          allowed_origins:
            - https://shadowapi.devinlab.com
          allowed_methods:
            - POST
            - GET
            - PUT
            - PATCH
            - DELETE
          allowed_headers:
            - Authorization
            - Cookie
            - Content-Type
          exposed_headers:
            - Content-Type
            - Set-Cookie
      admin:
        base_url: https://shadowapi.devinlab.com/auth/admin
    
    selfservice:
      default_browser_return_url: https://shadowapi.devinlab.com/
      allowed_return_urls:
        - https://shadowapi.devinlab.com/
      
      methods:
        password:
          enabled: true
        totp:
          config:
            issuer: ShadowAPI
          enabled: true
        lookup_secret:
          enabled: true
        link:
          enabled: true
        code:
          enabled: true
      
      flows:
        error:
          ui_url: https://shadowapi.devinlab.com/error
        
        settings:
          ui_url: https://shadowapi.devinlab.com/settings
          privileged_session_max_age: 15m
          required_aal: highest_available
        
        recovery:
          enabled: true
          ui_url: https://shadowapi.devinlab.com/recovery
          use: code
        
        verification:
          enabled: true
          ui_url: https://shadowapi.devinlab.com/verification
          use: code
          after:
            default_browser_return_url: https://shadowapi.devinlab.com/
        
        logout:
          after:
            default_browser_return_url: https://shadowapi.devinlab.com/login
        
        login:
          ui_url: https://shadowapi.devinlab.com/login
          lifespan: 10m
        
        registration:
          lifespan: 10m
          ui_url: https://shadowapi.devinlab.com/registration
          after:
            default_browser_return_url: https://shadowapi.devinlab.com/
    
    log:
      level: info
      format: text
      leak_sensitive_values: false
    
    secrets:
      cookie:
        - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
      cipher:
        - 32-LONG-SECRET-NOT-SECURE-AT-ALL
    
    ciphers:
      algorithm: xchacha20-poly1305
    
    hashers:
      algorithm: bcrypt
      bcrypt:
        cost: 8
    
    identity:
      default_schema_id: default
      schemas:
        - id: default
          url: file:///etc/config/identity.schema.json
  
  identity.schema.json: |
    {
      "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Person",
      "type": "object",
      "properties": {
        "traits": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "format": "email",
              "title": "E-Mail",
              "minLength": 3,
              "ory.sh/kratos": {
                "credentials": {
                  "password": {
                    "identifier": true
                  }
                },
                "verification": {
                  "via": "email"
                },
                "recovery": {
                  "via": "email"
                }
              }
            },
            "name": {
              "type": "object",
              "properties": {
                "first": {
                  "title": "First Name",
                  "type": "string"
                },
                "last": {
                  "title": "Last Name",
                  "type": "string"
                }
              }
            }
          },
          "required": [
            "email"
          ],
          "additionalProperties": false
        }
      }
    }