apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shadowapi

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - nats.yaml
  - frontend.yaml
  - backend.yaml
  - backend-loader.yaml
  - kratos.yaml
  - migrations.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: shadowapi
  app.kubernetes.io/version: latest
