version: v0.13.0

serve:
  public:
    base_url: http://localtest.me/auth/user/
    cors:
      enabled: true
  admin:
    base_url: http://localtest.me/auth/admin/

session:
  whoami:
    required_aal: aal1

selfservice:
  default_browser_return_url: http://localtest.me/
  allowed_return_urls:
    - http://localtest.me/
    - http://localtest.me/callback

  methods:
    password:
      enabled: true

  flows:
    error:
      ui_url: http://localtest.me/error

    settings:
      ui_url: http://localtest.me/settings
      privileged_session_max_age: 15m
      required_aal: aal1

    recovery:
      enabled: true
      ui_url: http://localtest.me/recovery
      use: code

    verification:
      enabled: false
      ui_url: http://localtest.me/verification
      use: code
      after:
        default_browser_return_url: http://localtest.me/

    logout:
      after:
        default_browser_return_url: http://localtest.me/login

    login:
      ui_url: http://localtest.me/login
      lifespan: 10m

    registration:
      enable_legacy_one_step: false
      lifespan: 10m
      ui_url: http://localtest.me/signup
      after:
        passkey:
          hooks:
            - hook: session
        webauthn:
          hooks:
            - hook: session
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - bf072359ea71a37f22099682a0e80422
  cipher:
    - 98cb3b714820a281838ab6b5d23a2b9d

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///home/ory/identity.schema.json
