get:
  summary: List pipelines
  description: Get all pipelines for the current user
  operationId: pipeline-list
  parameters:
    - name: datasource_uuid
      in: query
      description: Filter pipelines by datasource UUID
      required: false
      schema:
        type: string
        format: uuid
    - description: Offset records.
      in: query
      name: offset
      schema:
        type: integer
        format: int32
    - description: Limit records.
      in: query
      name: limit
      schema:
        type: integer
        format: int32
  responses:
    '200':
      description: List of pipelines
      content:
        application/json:
          schema:
            type: object
            properties:
              pipelines:
                type: array
                items:
                  $ref: "../openapi.yaml#/components/schemas/Pipeline"
            required:
              - pipelines
    default:
      description: Error
      content:
        application/json:
          schema:
            $ref: "../openapi.yaml#/components/schemas/Error"
  tags:
    - pipeline

post:
  summary: Create a new pipeline
  description: Create a new pipeline for a datasource
  operationId: pipeline-create
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../openapi.yaml#/components/schemas/Pipeline"
  responses:
    '201':
      description: Pipeline created successfully
      content:
        application/json:
          schema:
            $ref: "../openapi.yaml#/components/schemas/Pipeline"
    default:
      description: Error
      content:
        application/json:
          schema:
            $ref: "../openapi.yaml#/components/schemas/Error"
  tags:
    - pipeline