get:
  description: List pipelines
  operationId: pipeline-list
  parameters:
    - description: Offset records.
      in: query
      name: offset
      explode: false
      schema:
        description: Offset records.
        format: int32
        type: integer
    - description: Limit records.
      in: query
      name: limit
      explode: false
      schema:
        description: Limit records.
        format: int32
        type: integer
  responses:
    "200":
      description: Pipelines retrieved successfully.
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              pipelines:
                description: List of pipelines.
                type: array
                items:
                  $ref: "../openapi.yaml#/components/schemas/Pipeline"
            required:
              - pipelines
    default:
      description: Error
      content:
        application/json:
          schema:
            $ref: "../openapi.yaml#/components/schemas/Error"
  tags:
    - pipeline

post:
  description: Create Pipeline
  operationId: pipeline-create
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          additionalProperties: false
          properties:
            user_uuid:
              type: string
              description: The user or account that owns this pipeline.
            name:
              type: string
              description: Name of the pipeline.
            flow:
              type: object
              additionalProperties: true
              description: Flow JSON to draw.
          required:
            - name
            - flow
  responses:
    "200":
      description: Pipeline created successfully.
      content:
        application/json:
          schema:
            $ref: "../openapi.yaml#/components/schemas/Pipeline"
    default:
      description: Error
      content:
        application/json:
          schema:
            $ref: "../openapi.yaml#/components/schemas/Error"
  tags:
    - pipeline
