apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shadowapi-staging

resources:
  - ../../base

namePrefix: staging-

patchesStrategicMerge:
  - patches/staging-config.yaml

commonLabels:
  environment: staging

replacements:
  - source:
      kind: ConfigMap
      name: shadowapi-config
      fieldPath: data.SA_BASE_URL
    targets:
      - select:
          kind: Secret
          name: shadowapi-app
        fieldPaths:
          - stringData.SA_BASE_URL

